name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@v3.3.2
        # only publish if a direct `push`/`repository_dispatch`
        # publish non-production deploy if it's a fork
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}